on: push
name: 🚀 Deploy PWA on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup pnpm
        run: |
          npm i -g pnpm

      - name: 🔨 Build Project
        run: |
          pnpm install
          pnpm ng build
          
      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.username }}
            server: ${{ secrets.host }}
            ssh_private_key: ${{ secrets.ssh }} 
            local_path: './frontend/dist/frontend/*'
            remote_path: '/home/${{ secrets.username }}/PJPL/PWA'
          
      - name: 🚚 Replace PWA files in apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.ssh }}
          port: 22
          script: |
           cd /var/www/html
           rm *.js
           rm *.html
           rm *.css
           rm -r assets
           cp -r /home/ubuntu/PJPL/PWA/* . 
